INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (1, 'Recepcionar solicitud ','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (2, 'Recibir, verificar y asignar la Solicitud','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (3, 'Analizar la queja, anónimo, informe y/o publicación respectiva ','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (4, 'Realizar Auto Inhibitorio','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (5, 'Revisar y aprobar auto inhibitorio','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (6, 'Comunicar al quejoso  ','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (7, 'Revisar y aprobar memorando y/o oficio','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (8, 'Archivar documentos al expediente','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (9, 'Retornar al Fin del Proceso','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (10, 'Realizar auto de Inicio de Indagación Previa ','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (11, 'Revisar y aprobar auto de indagación previa','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (12, 'Comunicar al quejoso o informante','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (13, 'Revisar y aprobar memorando y/o oficio','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (14, 'Solicitar, recaudar y analizar pruebas','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (15, 'Revisar y aprobar documentos de pruebas','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (16, 'Elaborar auto de archivo, oficio y memorando','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (17, 'Revisar y aprobar documentos de archivo de indagación previa','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (18, 'Comunicar al quejoso o informante','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (19, 'Archivar documentos al expediente','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (20, 'Realizar constancia ejecutoria','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (21, 'Retornar al Fin del Proceso','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (22, 'Recepcionar Recurso de Apelación','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (23, 'Elaborar constancia secretarial','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (24, 'Archivar documentos al expediente','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (25, 'Retornar al Fin del Proceso','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (26, 'Elaborar auto remisorio','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (27, 'Elaborar memorando','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (28, 'Revisar y aprobar auto y memorando remisorio','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (29, 'Elaborar Auto de Inicio de Investigación disciplinaria, oficios y memorandos','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (30, 'Realizar auto de cumplimiento de segunda instancia','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (31, 'Revisar y aprobar auto de cumplimiento de segunda instancia','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (32, 'Realizar constancia secretarial','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (33, 'Archivar documentos al expediente','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (34, 'Retornar al Fin del Proceso','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (35, 'Elaborar Auto de Inicio de Investigación disciplinaria, oficios y memorandos','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (36, 'Revisar y aprobar documentos de inicio de investigación disciplinaria','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (37, 'Notificar el auto de inicio y de vinculación a la investigación disciplinaria','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (38, 'Iniciar trámite de confesión','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (39, 'Recepcionar y valorar la confesión','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (40, 'Enviar auto a director de Juzgamiento','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (41, 'Solicitar y asignar abogado de oficio para diligencia de confesión','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (42, 'Revisar y aprobar documentos de asignación de abogado de oficio','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (43, 'Comparecer a la asignación','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (44, 'Revisar y aprobar auto de reconocimiento de personería jurídica','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (45, 'Solicitar y recaudar pruebas','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (46, 'Revisar y aprobar documentos de pruebas','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (47, 'Proferir auto de cierre de investigación y alegatos precalificatorios','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (48, 'Revisar y aprobar auto de cierre de investigación y alegatos precalificatorios','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (49, 'Notificar a sujetos procesales','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (50, 'Realizar constancia secretarial','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (51, 'Elaborar auto de archivo de investigación disciplinaria, oficios, memorandos ','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (52, 'Revisar y aprobar documentos de archivo de investigación disciplinaria','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (53, 'Notificar archivo de investigación disciplinaria','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (54, 'Archivar documentos al expediente','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (55, 'Realizar constancia secretarial','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (56, 'Archivar documentos al expediente','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (57, 'Retornar al Fin del Proceso','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (58, 'Recepcionar Recurso de Apelación','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (59, 'Elaborar constancia secretarial','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (60, 'Archivar documentos al expediente','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (61, 'Retornar al Fin del Proceso','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (62, 'Elaborar auto remisorio','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (63, 'Elaborar memorando','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (64, 'Revisar y aprobar auto y memorando remisorio','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (65, 'Realizar auto de cumplimiento de segunda instancia','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (66, 'Revisar y aprobar auto de cumplimiento de segunda instancia','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (67, 'Realizar constancia ejecutoria','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (68, 'Archivar documentos al expediente','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (69, 'Retornar al Fin del Proceso','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (70, 'Proferir pliego de cargos  ','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (71, 'Revisar y aprobar auto de cargos','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (72, 'Notificar al disciplinado y/o apoderado','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (73, 'Archivar documentos al expediente','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (74, 'Enviar auto a director de Juzgamiento','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (75, 'Recibir proceso disciplinario  de la Dirección de Instrucción','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (76, 'Analizar y definir medio de juzgamiento','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (77, 'Comunicar auto de sustanciación','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (78, 'Recibir y analizar descargos','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (79, 'Revisar y aprobar auto vario aprobación/negación de pruebas','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (80, 'Comunicar auto vario aprobación pruebas','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (81, 'Practicar pruebas','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (82, 'Cerrar etapa probatoria','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (83, 'Revisar y aprobar auto para traslado de alegatos de conclusión','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (84, 'Comunicar auto Interlocutorio','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (85, 'Elaborar constancia de alegatos','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (86, 'Elaborar auto de fallo (ordinario)','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (87, 'Revisar y aprobar auto de fallo','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (88, 'Comunicar y notificar auto de fallo ','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (89, 'Realizar constancia de no apelación al fallo','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (90, 'Elaborar oficio remisorio de ejecución sanción al nominador','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (91, 'Revisar y aprobar oficio remisorio ejecución sanción','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (92, 'Recibir resolución y comunicar efectos de  sanción a entes de control  ','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (93, 'Revisar y aprobar documentos de comunicación de efectos de sanción','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (94, 'Verificar cumplimiento de sanción','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (95, 'Revisar y aprobar documentos de reiteración de cumplimiento de sanción','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (96, 'Archivar documentos al expediente','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (97, 'Retornar al Fin del Proceso','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (98, 'Realizar constancia de presentación de recurso de apelación de fallo y elaborar auto y memorando remisorio','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (99, 'Revisar y aprobar documentos de remisión de apelación al fallo','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (100, 'Notificar auto vario de negación de pruebas ','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (101, 'Recibir recurso','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (102, 'Elaborar auto de trámite ','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (103, 'Revisar y aprobar auto de trámite','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (104, 'Elaborar auto de cumplimiento a lo resuelto por la segunda instancia','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (105, 'Comunicar auto de lo resuelto por la segunda instancia','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (106, 'Elaborar constancia secretarial ','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (107, 'Comunicar auto de sustanciación','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (108, 'Programar fecha de citación audiencia','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (109, 'Comunicar memorando de citación audiencia','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (110, 'Realizar Primera Audiencia','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (111, 'Cumplir con requisitos de Ley de la Confesión','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (112, 'Proyectar y notificar fallo ','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (113, 'Realizar constancia de no apelación al fallo','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (114, 'Elaborar oficio remisorio de ejecución sanción al nominador','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (115, 'Revisar y aprobar oficio remisorio ejecución sanción','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (116, 'Recibir resolución y comunicar efectos de  sanción a entes de control  ','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (117, 'Revisar y aprobar documentos de comunicación de efectos de sanción','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (118, 'Verificar cumplimiento de sanción','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (119, 'Revisar y aprobar documentos de reiteración de cumplimiento de sanción','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (120, 'Archivar documentos al expediente','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (121, 'Retornar al Fin del Proceso','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (122, 'Realizar constancia y recibir sustentación de apelación de fallo','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (123, 'Elaborar auto remisorio y memorando de apelación del fallo ','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (124, 'Revisar y aprobar documentos de remisión de apelación al fallo','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (125, 'Recibir resolución y comunicar efectos de  sanción a entes de control  ','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (126, 'Revisar y aprobar documentos de comunicación de efectos de sanción','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (127, 'Verificar cumplimiento de sanción','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (128, 'Revisar y aprobar documentos de reiteración de cumplimiento de sanción','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (129, 'Archivar documentos al expediente','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (130, 'Retornar al Fin del Proceso','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (131, 'Elaborar auto de cumplimiento de resolución de segunda instancia','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (132, 'Comunicar auto de cumplimiento de resolución de segunda instancia','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (133, 'Cumplir con requisitos de Ley de la Confesión','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (134, 'Cerrar etapa probatoria','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (135, 'Realizar audiencia de alegatos previos al fallo','TBD', 'Instrucción');
INSERT INTO public."requestState"(id, "stateName", "stageName", "faseName") VALUES (136, 'Realizar audiencia de lectura de fallo ','TBD', 'Instrucción');
